// <auto-generated />
using System;
using HairSalon_Booking_Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HairSalon_Booking_Engine.Migrations
{
    [DbContext(typeof(HairSalonDBContext))]
    [Migration("20260604003944_UpdatedSeedData")]
    partial class UpdatedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTreatment", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentsId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "TreatmentsId");

                    b.HasIndex("TreatmentsId");

                    b.ToTable("BookingTreatment");

                    b.HasData(
                        new
                        {
                            BookingsId = 1,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 2,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 3,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 4,
                            TreatmentsId = 6
                        },
                        new
                        {
                            BookingsId = 5,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 5,
                            TreatmentsId = 8
                        },
                        new
                        {
                            BookingsId = 6,
                            TreatmentsId = 4
                        },
                        new
                        {
                            BookingsId = 7,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 8,
                            TreatmentsId = 5
                        },
                        new
                        {
                            BookingsId = 9,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 10,
                            TreatmentsId = 8
                        },
                        new
                        {
                            BookingsId = 11,
                            TreatmentsId = 7
                        },
                        new
                        {
                            BookingsId = 12,
                            TreatmentsId = 9
                        },
                        new
                        {
                            BookingsId = 13,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 14,
                            TreatmentsId = 5
                        },
                        new
                        {
                            BookingsId = 15,
                            TreatmentsId = 6
                        },
                        new
                        {
                            BookingsId = 16,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 17,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 18,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 19,
                            TreatmentsId = 4
                        },
                        new
                        {
                            BookingsId = 20,
                            TreatmentsId = 6
                        },
                        new
                        {
                            BookingsId = 21,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 22,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 23,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 24,
                            TreatmentsId = 8
                        },
                        new
                        {
                            BookingsId = 25,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 26,
                            TreatmentsId = 9
                        },
                        new
                        {
                            BookingsId = 27,
                            TreatmentsId = 4
                        },
                        new
                        {
                            BookingsId = 28,
                            TreatmentsId = 5
                        },
                        new
                        {
                            BookingsId = 29,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 30,
                            TreatmentsId = 7
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 2, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 3, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 3, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 6, 4, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 4, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 4, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 6, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 5, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 5, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 8, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 11, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 6, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 11, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 11, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 12, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 6, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            EndTime = new DateTime(2026, 6, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            EndTime = new DateTime(2026, 6, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            EndTime = new DateTime(2026, 6, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StylistId = 3
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emma.johansson@example.com",
                            FirstName = "Emma",
                            LastName = "Johansson",
                            Phone = "070-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lucas.berg@example.com",
                            FirstName = "Lucas",
                            LastName = "Berg",
                            Phone = "073-234 56 78"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Maja",
                            LastName = "Nilsson",
                            Phone = "076-345 67 89"
                        },
                        new
                        {
                            Id = 4,
                            Email = "oliver.svensson@example.com",
                            FirstName = "Oliver",
                            LastName = "Svensson",
                            Phone = "070-456 78 90"
                        },
                        new
                        {
                            Id = 5,
                            Email = "astrid.eriksson@example.com",
                            FirstName = "Astrid",
                            LastName = "Eriksson",
                            Phone = "073-567 89 01"
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("LunchTime")
                        .HasColumnType("time");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("StylistId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 1,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 1,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 4,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 1,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 3,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 2,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 2,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 3,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 4,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 3,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 5,
                            LunchTime = new TimeOnly(12, 0, 0),
                            StylistId = 3,
                            WorkEnd = new TimeOnly(17, 0, 0),
                            WorkStart = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stylist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sofia",
                            LastName = "Andersson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Marcus",
                            LastName = "Lindqvist"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Isabelle",
                            LastName = "Karlsson"
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Precision cut with a full blowdry finish.",
                            DurationMin = 60,
                            Name = "Women's Cut & Blowdry",
                            Price = 650m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic scissor or clipper cut.",
                            DurationMin = 30,
                            Name = "Men's Cut",
                            Price = 350m
                        },
                        new
                        {
                            Id = 3,
                            Description = "All-over colour with premium tint.",
                            DurationMin = 90,
                            Name = "Full Colour",
                            Price = 950m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Foil highlights on the top and crown sections.",
                            DurationMin = 75,
                            Name = "Highlights – Half Head",
                            Price = 800m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Foil highlights throughout the entire head.",
                            DurationMin = 105,
                            Name = "Highlights – Full Head",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hand-painted freehand lightening technique.",
                            DurationMin = 120,
                            Name = "Balayage",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Smoothing treatment for frizz-free, glossy hair.",
                            DurationMin = 150,
                            Name = "Keratin Treatment",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Intensive repair mask with steam application.",
                            DurationMin = 30,
                            Name = "Deep Conditioning Mask",
                            Price = 250m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Relaxed cut for children aged 12 and under.",
                            DurationMin = 30,
                            Name = "Children's Cut (<=12)",
                            Price = 250m
                        });
                });

            modelBuilder.Entity("BookingTreatment", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Booking", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Stylist", "Stylist")
                        .WithMany("Bookings")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Schedule", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Stylist", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
