// <auto-generated />
using System;
using HairSalon_Booking_Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HairSalon_Booking_Engine.Migrations
{
    [DbContext(typeof(HairSalonDBContext))]
    [Migration("20260507101958_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTreatment", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentsId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "TreatmentsId");

                    b.HasIndex("TreatmentsId");

                    b.ToTable("BookingTreatment");

                    b.HasData(
                        new
                        {
                            BookingsId = 1,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 1,
                            TreatmentsId = 8
                        },
                        new
                        {
                            BookingsId = 2,
                            TreatmentsId = 2
                        },
                        new
                        {
                            BookingsId = 3,
                            TreatmentsId = 6
                        },
                        new
                        {
                            BookingsId = 3,
                            TreatmentsId = 1
                        },
                        new
                        {
                            BookingsId = 4,
                            TreatmentsId = 3
                        },
                        new
                        {
                            BookingsId = 5,
                            TreatmentsId = 5
                        },
                        new
                        {
                            BookingsId = 5,
                            TreatmentsId = 8
                        },
                        new
                        {
                            BookingsId = 6,
                            TreatmentsId = 7
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookedDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 14, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookedDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookedDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookedDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookedDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingDate = new DateTime(2025, 5, 22, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            StylistId = 3
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emma.johansson@example.com",
                            FirstName = "Emma",
                            LastName = "Johansson",
                            Phone = "070-123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lucas.berg@example.com",
                            FirstName = "Lucas",
                            LastName = "Berg",
                            Phone = "073-234 56 78"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Maja",
                            LastName = "Nilsson",
                            Phone = "076-345 67 89"
                        },
                        new
                        {
                            Id = 4,
                            Email = "oliver.svensson@example.com",
                            FirstName = "Oliver",
                            LastName = "Svensson",
                            Phone = "070-456 78 90"
                        },
                        new
                        {
                            Id = 5,
                            Email = "astrid.eriksson@example.com",
                            FirstName = "Astrid",
                            LastName = "Eriksson",
                            Phone = "073-567 89 01"
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Kérastase",
                            Description = "Sulphate-free shampoo for dry or colour-treated hair.",
                            Name = "Hydrating Shampoo 250 ml",
                            Price = 299m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kérastase",
                            Description = "Rich conditioner that rebuilds damaged hair fibre.",
                            Name = "Repair Conditioner 200 ml",
                            Price = 319m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Moroccanoil",
                            Description = "Lightweight serum for shine and frizz control.",
                            Name = "Argan Oil Serum 100 ml",
                            Price = 389m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Redken",
                            Description = "Heat-activated mousse for lasting lift and body.",
                            Name = "Volumising Mousse 200 ml",
                            Price = 229m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Redken",
                            Description = "Protects up to 230 °C from heat styling damage.",
                            Name = "Heat Protectant Spray 150 ml",
                            Price = 249m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Fanola",
                            Description = "Neutralises brassy tones in blonde and grey hair.",
                            Name = "Purple Toning Shampoo 250 ml",
                            Price = 179m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Davines",
                            Description = "Exfoliating scrub that removes build-up and balances scalp.",
                            Name = "Scalp Scrub 150 ml",
                            Price = 269m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Ouidad",
                            Description = "Nourishing cream that enhances and defines natural curls.",
                            Name = "Defining Curl Cream 200 ml",
                            Price = 299m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stylist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sofia",
                            LastName = "Andersson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Marcus",
                            LastName = "Lindqvist"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Isabelle",
                            LastName = "Karlsson"
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 900m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Date = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 578m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Date = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 2050m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            Date = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 1249m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            Date = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 1400m
                        });
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Precision cut with a full blowdry finish.",
                            Duration = 60,
                            Name = "Women's Cut & Blowdry",
                            Price = 650m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic scissor or clipper cut.",
                            Duration = 30,
                            Name = "Men's Cut",
                            Price = 350m
                        },
                        new
                        {
                            Id = 3,
                            Description = "All-over colour with premium tint.",
                            Duration = 90,
                            Name = "Full Colour",
                            Price = 950m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Foil highlights on the top and crown sections.",
                            Duration = 75,
                            Name = "Highlights – Half Head",
                            Price = 800m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Foil highlights throughout the entire head.",
                            Duration = 105,
                            Name = "Highlights – Full Head",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hand-painted freehand lightening technique.",
                            Duration = 120,
                            Name = "Balayage",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Smoothing treatment for frizz-free, glossy hair.",
                            Duration = 150,
                            Name = "Keratin Treatment",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Intensive repair mask with steam application.",
                            Duration = 30,
                            Name = "Deep Conditioning Mask",
                            Price = 250m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Relaxed cut for children aged 12 and under.",
                            Duration = 30,
                            Name = "Children's Cut (≤12)",
                            Price = 250m
                        });
                });

            modelBuilder.Entity("ProductTransaction", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TransactionsId");

                    b.HasIndex("TransactionsId");

                    b.ToTable("ProductTransaction");

                    b.HasData(
                        new
                        {
                            ProductsId = 3,
                            TransactionsId = 2
                        },
                        new
                        {
                            ProductsId = 5,
                            TransactionsId = 4
                        },
                        new
                        {
                            ProductsId = 6,
                            TransactionsId = 3
                        },
                        new
                        {
                            ProductsId = 1,
                            TransactionsId = 5
                        },
                        new
                        {
                            ProductsId = 2,
                            TransactionsId = 5
                        });
                });

            modelBuilder.Entity("TransactionTreatment", b =>
                {
                    b.Property<int>("TransactionsId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentsId")
                        .HasColumnType("int");

                    b.HasKey("TransactionsId", "TreatmentsId");

                    b.HasIndex("TreatmentsId");

                    b.ToTable("TransactionTreatment");

                    b.HasData(
                        new
                        {
                            TransactionsId = 1,
                            TreatmentsId = 1
                        },
                        new
                        {
                            TransactionsId = 1,
                            TreatmentsId = 8
                        },
                        new
                        {
                            TransactionsId = 2,
                            TreatmentsId = 2
                        },
                        new
                        {
                            TransactionsId = 3,
                            TreatmentsId = 6
                        },
                        new
                        {
                            TransactionsId = 3,
                            TreatmentsId = 1
                        },
                        new
                        {
                            TransactionsId = 4,
                            TreatmentsId = 3
                        },
                        new
                        {
                            TransactionsId = 5,
                            TreatmentsId = 5
                        },
                        new
                        {
                            TransactionsId = 5,
                            TreatmentsId = 8
                        });
                });

            modelBuilder.Entity("BookingTreatment", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Booking", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Stylist", "Stylist")
                        .WithMany("Bookings")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Transaction", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProductTransaction", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransactionTreatment", b =>
                {
                    b.HasOne("HairSalon_Booking_Engine.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalon_Booking_Engine.Models.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HairSalon_Booking_Engine.Models.Stylist", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
