# Use this workspace to collaborate
workspace:
  id: 990a68d8-9879-4e2f-8bf8-dd68679171aa

# All resources in the `postman/` folder are automatically registered in Local View.
# Point to additional files outside the `postman/` folder to register them individually. Example:
#localResources:
#  collections:
#    - ../tests/E2E Test Collection/
